=== hamzaanis10/xml/index.dtd
<!ELEMENT students (name, age, email*, id, fees?, address+)>
    <!ELEMENT name (first_name, last_name)>
    <!ELEMENT first_name (#PCDATA)>
    <!ELEMENT last_name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT fees (#PCDATA)>
    <!ATTLIST address home CDATA #REQUIRED>
    <!ATTLIST address office CDATA #IMPLIED>
    <!ENTITY nbsp "#hamza">
    <!ENTITY writer "Donald Trump">

=== hamzaanis10/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "index.dtd" [

]>


<students>
    <name>
        <first_name></first_name>
        <last_name></last_name>
    </name>
    <age>19</age>
    <email>hamzaanis2014@gmail.com &writer;</email>
    <email>hamza@domain.com</email>
    <id>3</id>
    <address home="home address" office="office address">f 26 block f</address>
</students>
